version: '3.8'

services:
    postgres:
        image: postgres:14
        container_name: postgres
        environment:
            POSTGRES_USER: pulse
            POSTGRES_PASSWORD: p@ssw0rd
            POSTGRES_DB: pulsedb
        networks:
            - pulse
        volumes:
            - postgres_data:/var/lib/postgresql/data
        ports:
            - '5432:5432'

    grafana:
        image: grafana/grafana:latest
        container_name: grafana
        depends_on:
            - postgres
        environment:
            - GF_SECURITY_ADMIN_PASSWORD=admin
            - GF_SECURITY_ADMIN_USER=pulse
        networks:
            - pulse
        ports:
            - '3000:3000'
        volumes:
            - grafana_data:/var/lib/grafana

    backend:
        build:
            context: ./
        container_name: backend
        depends_on:
            - postgres
        networks:
            - pulse
        volumes:
            - ./frontend/build:/app/frontend/build
        ports:
            - '8080:8080'

networks:
    pulse:
        driver: bridge

volumes:
    postgres_data:
    grafana_data:
