version: '3.8'

services:
  postgres:
    image: postgres:14
    container_name: postgres
    environment:
      POSTGRES_USER: pulse   
      POSTGRES_PASSWORD: pulse
      POSTGRES_DB: pulse    
    networks:
      - pulse
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    depends_on:
      - postgres
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin 
      - GF_SECURITY_ADMIN_USER=pulse  
    networks:
      - pulse
    ports:
      - "3000:3000"
    volumes:
      - grafana_data:/var/lib/grafana

networks:
  pulse:
    driver: bridge

volumes:
  postgres_data:
  grafana_data:
