{
 "title": "Pulse",
 "time": { "from": "1970-01-01T00:00:00.000Z", "to": "1970-01-01T00:00:00.038Z" },
 "templating": {
  "list": [
   { "name": "pulsedatasource", "label": "Datasource", "query": "grafana-postgresql-datasource" },
   {
    "name": "identifier",
    "label": "Identifier",
    "query": "SELECT DISTINCT(identifier) FROM sessions"
   },
   {
    "name": "version",
    "label": "Version",
    "query": "SELECT DISTINCT(version) FROM sessions WHERE identifier = '$identifier'"
   },
   {
    "name": "platform",
    "label": "Platform",
    "query": "SELECT DISTINCT(platform) FROM public.sessions WHERE identifier ='$identifier' AND version = '$version'"
   },
   {
    "name": "device",
    "label": "Device",
    "query": "SELECT DISTINCT(device) FROM sessions WHERE identifier = '$identifier' AND version = '$version' AND platform = '$platform'"
   },
   {
    "name": "session",
    "label": "Sessions",
    "query": "SELECT DISTINCT(session) FROM sessions WHERE identifier = '$identifier' AND version = '$version' AND platform = '$platform' AND device ='$device'"
   }
  ]
 },
 "panels": [
  {
   "title": "FPS ${session:singlequote}",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "repeat": "session",
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "SELECT \"timestamp\" - MIN(\"timestamp\") OVER (PARTITION BY session) AS time, fps FROM datas WHERE session IN (${session:singlequote})"
    }
   ]
  },
  {
   "title": "System Memory ${session:singlequote}",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 8 },
   "repeat": "session",
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "rawSql": "SELECT \"timestamp\" - MIN(\"timestamp\") OVER (PARTITION BY session) AS time, \nsystem_used_memory, \ntotal_used_memory, \ngc_used_memory, \naudio_used_memory, \nvideo_used_memory,\nprofiler_used_memory FROM datas WHERE session IN (${session:singlequote})"
    }
   ]
  },
  {
   "title": "Render Counts ${session:singlequote}",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "repeat": "session",
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "SELECT \"timestamp\" - MIN(\"timestamp\") OVER (PARTITION BY session) AS time, \nset_pass_calls_count \ndraw_calls_count,\ntotal_batches_count,\ntriangles_count,\nvertices_count,\nrender_textures_count,\nrender_textures_changes_count,\nused_buffers_count,\nused_shaders_count,\nvertex_buffer_upload_in_frame_count,\nindex_buffer_upload_in_frame_count,\nshadow_casters_count\nFROM datas WHERE session IN (${session:singlequote})"
    }
   ]
  },
  {
   "title": "Render Memory ${session:singlequote}",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "repeat": "session",
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "rawSql": "SELECT \"timestamp\" - MIN(\"timestamp\") OVER (PARTITION BY session) AS time, \nrender_textures_bytes, used_buffers_bytes, vertex_buffer_upload_in_frame_bytes, index_buffer_upload_in_frame_bytes\nprofiler_used_memory FROM datas WHERE session IN (${session:singlequote})"
    }
   ]
  }
 ]
}